### ISSUE TITLE
Multiple instances of radosgw fills conntrack table in seconds

### ISSUE THREAD

**Issue by mustafa-muhammad** [ceph/ceph-docker#51] opened 2015-03-25 17:55 UTC
I am testing this docker container, thank you, but I have a problem, when I run multiple instances, suddenly the conntrack table gets filled.
e.g. I run one instance, sometimes 2, and nothing wrong, also:
#cat /proc/sys/net/netfilter/nf_conntrack_count 
gives me less than 100
but after one or two more instances, nf_conntrack_count  increases very quickly, and after a few seconds it reaches 65k, I tried increasing it to 256k but it gets filled in seconds too.

**Comment by Ulexus** [comment] 2015-03-25 19:43
This is almost certainly a duplicate of #19

The symptoms are the same, it's just a different module.  I'm going to close this as a duplicate, but do you have a use-case where multiple instances of radosgw are needed from a single host?

**Closed by Ulexus** 2015-03-25 19:43 UTC

**Comment by mustafa-muhammad** [comment] 2015-03-26 07:18
I have multiple (thousands) of long connections (downloading multiple GBs at about 400KB/s), this is causing problems when I use one radosgw for more than about 500 connections.
So scaling horizontally is important, now I use virtual machines but I wanted to use docker instead.
Also this is the beauty of Docker, you can have multiple instances without affecting each other, start some and terminate others on demand.

**Comment by mustafa-muhammad** [comment] 2015-03-26 09:53
As a workaround, I confirm that using "--pid host" solves the issue for me, I run over 20 instances with:
docker run -d --pid host -p 80:80 -e RGW_NAME=myrgw -v /etc/ceph:/etc/ceph ceph/radosgw
only changing the ports.
